/// Flutter icons HomeButton
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HomeButton
///      fonts:
///       - asset: fonts/HomeButton.ttf
///
///
///
import 'package:flutter/widgets.dart';

class DjangoButton {
  DjangoButton._();

  static const _kFontFam = 'DjangoButton';
  static const String? _kFontPkg = null;

  static const IconData django =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
