/// Flutter icons HomeButton
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HomeButton
///      fonts:
///       - asset: fonts/HomeButton.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class HomeButton {
  HomeButton._();

  static const _kFontFam = 'HomeButton';
  static const String? _kFontPkg = null;

  static const IconData flutter = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
