name: justary27_s_portfolio
description: "IITR'24 | Codifyin' Reality."

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.0+3

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.3.1
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  flutter_riverpod: ^2.6.1
  model_viewer_plus: ^1.9.3
  flutter_svg: ^2.1.0
  carousel_slider: ^5.0.0
  go_router: ^15.1.1
  flutter_circular_text: ^0.3.1
  pdfrx: ^1.1.27
  markdown_widget: ^2.3.2+8


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/
  - assets/images/
  - assets/models/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: Allison
    fonts:
    - asset: assets/fonts/Allison-Regular.ttf

  - family: Caveat
    fonts:
    - asset: assets/fonts/caveat/Caveat-Regular.ttf
    - asset: assets/fonts/caveat/Caveat-Bold.ttf
      weight: 700
    - asset: assets/fonts/caveat/Caveat-Medium.ttf
      weight: 500
    - asset: assets/fonts/caveat/Caveat-SemiBold.ttf
      weight: 600

  - family: ABeeZee
    fonts:
    - asset: assets/fonts/aBeeZee/ABeeZee-Regular.ttf
    - asset: assets/fonts/aBeeZee/ABeeZee-Italic.ttf
      style: italic

  - family: CoveredByYourGrace
    fonts:
    - asset: assets/fonts/coveredGrace/CoveredByYourGrace-Regular.ttf

  - family: Itim
    fonts:
    - asset: assets/fonts/itim/Itim-Regular.ttf

  - family: Ubuntu
    fonts:
    - asset: assets/fonts/ubuntu/Ubuntu-Regular.ttf
    - asset: assets/fonts/ubuntu/Ubuntu-Bold.ttf
      weight: 700
    - asset: assets/fonts/ubuntu/Ubuntu-BoldItalic.ttf
      weight: 700
      style: italic
    - asset: assets/fonts/ubuntu/Ubuntu-Medium.ttf
      weight: 500
    - asset: assets/fonts/ubuntu/Ubuntu-MediumItalic.ttf
      weight: 500
      style: italic
    - asset: assets/fonts/ubuntu/Ubuntu-Light.ttf
      weight: 300
    - asset: assets/fonts/ubuntu/Ubuntu-LightItalic.ttf
      weight: 300
      style: italic
    - asset: assets/fonts/ubuntu/Ubuntu-Italic.ttf
      style: italic

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
